package com.demo.repository.jdbc;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.Collection;
import java.util.List;

import javax.sql.DataSource;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;

import com.demo.model.Owner;
import com.demo.model.Pet;
import com.demo.model.PetType;
import com.demo.model.Specialty;
import com.demo.model.User;
import com.demo.model.Vet;
import com.demo.model.Visit;

/**
 * Characterization + coverage for JDBC {@code @Alternative} repositories.
 * Constructs beans with an embedded H2 DataSource (JPA path stays primary in CDI).
 */
class JdbcRepositoryCoverageTest {

    private DataSource dataSource;
    private JdbcOwnerRepositoryImpl owners;
    private JdbcPetRepositoryImpl pets;
    private JdbcPetTypeRepositoryImpl petTypes;
    private JdbcVisitRepositoryImpl visits;
    private JdbcVetRepositoryImpl vets;
    private JdbcSpecialtyRepositoryImpl specialties;
    private JdbcUserRepositoryImpl users;

    @BeforeEach
    void setUp() throws Exception {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:jdbc_cov_" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        ds.setPassword("");
        this.dataSource = ds;
        try (Connection c = ds.getConnection(); Statement st = c.createStatement()) {
            st.execute("DROP TABLE IF EXISTS vet_specialties");
            st.execute("DROP TABLE IF EXISTS roles");
            st.execute("DROP TABLE IF EXISTS users");
            st.execute("DROP TABLE IF EXISTS visits");
            st.execute("DROP TABLE IF EXISTS pets");
            st.execute("DROP TABLE IF EXISTS types");
            st.execute("DROP TABLE IF EXISTS owners");
            st.execute("DROP TABLE IF EXISTS specialties");
            st.execute("DROP TABLE IF EXISTS vets");
            st.execute("""
                CREATE TABLE vets (
                  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  first_name VARCHAR(30),
                  last_name VARCHAR(30)
                )
                """);
            st.execute("""
                CREATE TABLE specialties (
                  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  name VARCHAR(80)
                )
                """);
            st.execute("""
                CREATE TABLE vet_specialties (
                  vet_id INTEGER NOT NULL,
                  specialty_id INTEGER NOT NULL
                )
                """);
            st.execute("""
                CREATE TABLE types (
                  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  name VARCHAR(80)
                )
                """);
            st.execute("""
                CREATE TABLE owners (
                  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  first_name VARCHAR(30),
                  last_name VARCHAR(30),
                  address VARCHAR(255),
                  city VARCHAR(80),
                  telephone VARCHAR(20)
                )
                """);
            st.execute("""
                CREATE TABLE pets (
                  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  name VARCHAR(30),
                  birth_date DATE,
                  type_id INTEGER NOT NULL,
                  owner_id INTEGER NOT NULL
                )
                """);
            st.execute("""
                CREATE TABLE visits (
                  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  pet_id INTEGER NOT NULL,
                  visit_date DATE,
                  description VARCHAR(255)
                )
                """);
            st.execute("""
                CREATE TABLE users (
                  username VARCHAR(20) NOT NULL PRIMARY KEY,
                  password VARCHAR(20) NOT NULL,
                  enabled BOOLEAN DEFAULT TRUE NOT NULL
                )
                """);
            st.execute("""
                CREATE TABLE roles (
                  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  username VARCHAR(20) NOT NULL,
                  role VARCHAR(20) NOT NULL
                )
                """);
            st.execute("INSERT INTO types (id, name) VALUES (1, 'dog')");
            st.execute(
                "INSERT INTO owners (id, first_name, last_name, address, city, telephone) "
                    + "VALUES (1, 'Ada', 'Lovelace', '1 Analytical Eng', 'London', '555')");
            st.execute(
                "INSERT INTO pets (id, name, birth_date, type_id, owner_id) "
                    + "VALUES (1, 'Rex', DATE '2020-01-01', 1, 1)");
            st.execute(
                "INSERT INTO visits (id, pet_id, visit_date, description) "
                    + "VALUES (1, 1, DATE '2021-01-01', 'checkup')");
            st.execute("INSERT INTO specialties (id, name) VALUES (1, 'radiology')");
            st.execute(
                "INSERT INTO vets (id, first_name, last_name) VALUES (1, 'James', 'Carter')");
            st.execute("INSERT INTO vet_specialties (vet_id, specialty_id) VALUES (1, 1)");
            st.execute(
                "INSERT INTO users (username, password, enabled) VALUES ('admin', 'admin', TRUE)");
            st.execute("INSERT INTO roles (username, role) VALUES ('admin', 'ROLE_ADMIN')");
            for (String table : List.of("owners", "pets", "visits", "types", "vets", "specialties", "roles")) {
                st.execute("ALTER TABLE " + table + " ALTER COLUMN id RESTART WITH 100");
            }
        }
        owners = new JdbcOwnerRepositoryImpl(dataSource);
        pets = new JdbcPetRepositoryImpl(dataSource, owners);
        petTypes = new JdbcPetTypeRepositoryImpl(dataSource);
        visits = new JdbcVisitRepositoryImpl(dataSource);
        vets = new JdbcVetRepositoryImpl(dataSource, new JdbcTemplate(dataSource));
        specialties = new JdbcSpecialtyRepositoryImpl(dataSource);
        users = new JdbcUserRepositoryImpl(dataSource);
    }

    @Test
    void ownerFindAndSaveRoundTrip() {
        Collection<Owner> byName = owners.findByLastName("Love");
        assertFalse(byName.isEmpty());
        Owner found = owners.findById(1);
        assertEquals("Ada", found.getFirstName());
        assertNotNull(owners.findAll());
        Owner created = new Owner();
        created.setFirstName("Grace");
        created.setLastName("Hopper");
        created.setAddress("Navy");
        created.setCity("Arlington");
        created.setTelephone("123");
        owners.save(created);
        assertNotNull(created.getId());
        owners.delete(created);
    }

    @Test
    void petTypeAndPetVisitFlows() {
        List<PetType> types = pets.findPetTypes();
        assertEquals(1, types.size());
        Pet pet = pets.findById(1);
        assertEquals("Rex", pet.getName());
        assertNotNull(pets.findAll());
        PetType type = petTypes.findById(1);
        assertEquals("dog", type.getName());
        assertNotNull(petTypes.findAll());
        Visit visit = visits.findById(1);
        assertEquals("checkup", visit.getDescription());
        assertNotNull(visits.findAll());
        Visit created = new Visit();
        created.setDescription("booster");
        created.setDate(LocalDate.of(2022, 2, 2));
        created.setPet(pet);
        visits.save(created);
        assertNotNull(created.getId());
    }

    @Test
    void vetSpecialtyUserFlows() {
        Vet vet = vets.findById(1);
        assertEquals("Carter", vet.getLastName());
        assertFalse(vet.getSpecialties().isEmpty());
        assertNotNull(vets.findAll());
        Specialty spec = specialties.findById(1);
        assertEquals("radiology", spec.getName());
        assertNotNull(specialties.findAll());
        User user = new User();
        user.setUsername("coder");
        user.setPassword("secret");
        user.setEnabled(true);
        user.addRole("ROLE_USER");
        users.save(user);
        // update path
        user.setPassword("secret2");
        users.save(user);
    }

    @Test
    void rowMappersAndHelpers() throws Exception {
        try (Connection c = dataSource.getConnection();
            var ps = c.prepareStatement(
                "SELECT pets.id as pets_id, name, birth_date, type_id, owner_id FROM pets WHERE id=1");
            var rs = ps.executeQuery()) {
            assertTrue(rs.next());
            JdbcPet mapped = new JdbcPetRowMapper().mapRow(rs, 1);
            assertEquals(1, mapped.getId());
            assertEquals(1, mapped.getTypeId());
        }
        try (Connection c = dataSource.getConnection();
            var ps = c.prepareStatement(
                "SELECT id as visit_id, pet_id, visit_date, description FROM visits WHERE id=1");
            var rs = ps.executeQuery()) {
            assertTrue(rs.next());
            Visit mapped = new JdbcVisitRowMapper().mapRow(rs, 1);
            assertEquals("checkup", mapped.getDescription());
        }
        JdbcPet jp = new JdbcPet();
        jp.setId(9);
        jp.setTypeId(1);
        jp.setOwnerId(1);
        assertEquals(1, jp.getTypeId());
        assertEquals(1, jp.getOwnerId());
    }
}
